// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230525184440_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.Property<Guid>("ComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaEntregaId")
                        .HasColumnType("int");

                    b.Property<int>("PrecioTotal")
                        .HasColumnType("int");

                    b.HasKey("ComandaId");

                    b.HasIndex("FormaEntregaId");

                    b.ToTable("Comanda", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ComandaMercaderia", b =>
                {
                    b.Property<int>("ComandaMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComandaMercaderiaId"));

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MercaderiaId")
                        .HasColumnType("int");

                    b.HasKey("ComandaMercaderiaId");

                    b.HasIndex("ComandaId");

                    b.HasIndex("MercaderiaId");

                    b.ToTable("ComandaMercaderia", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FormaEntrega", b =>
                {
                    b.Property<int>("FormaEntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormaEntregaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FormaEntregaId");

                    b.ToTable("FormaEntrega", (string)null);

                    b.HasData(
                        new
                        {
                            FormaEntregaId = 1,
                            Descripcion = "Salon"
                        },
                        new
                        {
                            FormaEntregaId = 2,
                            Descripcion = "Delivery"
                        },
                        new
                        {
                            FormaEntregaId = 3,
                            Descripcion = "Pedidos Ya"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.Property<int>("MercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MercaderiaId"));

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Preparacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TipoMercaderiaId")
                        .HasColumnType("int");

                    b.HasKey("MercaderiaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("TipoMercaderiaId");

                    b.ToTable("Mercaderia", (string)null);

                    b.HasData(
                        new
                        {
                            MercaderiaId = 1,
                            Imagen = "https://img.freepik.com/foto-gratis/antipasto-varios-aperitivos-tabla-cortar-jamon-serrano-salami-coppa-queso-aceitunas-pared-gris-vista-superior_89816-11473.jpg?size=626&ext=jpg",
                            Ingredientes = "jamón crudo, salame, queso de cabra, aceitunas",
                            Nombre = "Tabla de fiambres",
                            Precio = 1500,
                            Preparacion = "Colocar los fiambres y el queso de cabra en una tabla de madera junto con las aceitunas. Servir frío.",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 2,
                            Imagen = "https://th.bing.com/th/id/OIP.vIA6RVih2inqxusXcrXYWgHaE7?pid=ImgDet&rs=1",
                            Ingredientes = "pechuga de pollo, pimiento rojo, pimiento verde, cebolla, aceite de oliva, sal, pimienta",
                            Nombre = "Pinchos de pollo",
                            Precio = 600,
                            Preparacion = "Cortar la pechuga de pollo en cubos y las verduras en trozos similares. En un recipiente, mezclar el aceite de oliva con la sal y la pimienta. Ensartar los cubos de pollo y los trozos de verduras en palitos de brochette y pintarlos con la mezcla de ace...",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 3,
                            Imagen = "https://i.pinimg.com/originals/02/fe/88/02fe8898eef54865652e7f64837c880e.jpg",
                            Ingredientes = "milanesa de carne, salsa de tomate, jamón cocido, queso mozzarella",
                            Nombre = "Milanesa napolitana",
                            Precio = 900,
                            Preparacion = "Freír la milanesa de carne y reservar. En una cacerola, calentar la salsa de tomate. Colocar la milanesa en una fuente para horno y cubrir con la salsa de tomate, jamón cocido y queso mozzarella. Llevar al horno precalentado a 180°C durante 10-15 minut...",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 4,
                            Imagen = "https://media-cdn.tripadvisor.com/media/photo-s/06/e3/d3/e6/ushuaia-frankfurt.jpg",
                            Ingredientes = "lomo de ternera, lechuga, tomate, mayonesa, pan francés",
                            Nombre = "Lomo completo",
                            Precio = 900,
                            Preparacion = "Cocinar el lomo a la parrilla o en una sartén. Cortar el pan en dos y tostarlo. Untar la mayonesa en el pan, colocar la lechuga y el tomate encima del pan. Colocar el lomo en el pan y cerrar.",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 5,
                            Imagen = "https://i2.wp.com/www.cocinaeficaz.com/wp-content/uploads/2016/09/%C3%B1oquis-de-papas-caseros-con-salsa-de-tomate.jpg?fit=800%2C598&ssl=1",
                            Ingredientes = "ñoquis, tomates perita, cebolla, ajo, aceite de oliva, sal, pimienta, queso parmesano",
                            Nombre = "Ñoquis con salsa de tomate casera",
                            Precio = 1000,
                            Preparacion = "Cocinar los ñoquis en agua hirviendo con sal hasta que estén al dente. En una sartén, dorar la cebolla y el ajo en aceite de oliva. Agregar los tomates perita picados y cocinar por unos minutos. Agregar sal y pimienta al gusto. Mezclar la salsa de toma...",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 6,
                            Imagen = "https://www.ricettaidea.it/articoli/ricette-regionali/lazio/original_spaghetti-alla-carbonara.jpg",
                            Ingredientes = "spaghetti, panceta, huevo, queso parmesano, aceite de oliva, sal, pimienta",
                            Nombre = "Spaghetti a la carbonara",
                            Precio = 1000,
                            Preparacion = "Cocinar los spaghetti en agua hirviendo con sal hasta que estén al dente. En una sartén, dorar la panceta en aceite de oliva. En un tazón, batir el huevo y agregar el queso parmesano rallado. Agregar la panceta y el aceite de oliva a la mezcla de huevo...",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 7,
                            Imagen = "https://th.bing.com/th/id/R.b02985c27cbf308e10a7b921b0c66a11?rik=ERI1ak13hDsmPg&pid=ImgRaw&r=0",
                            Ingredientes = "bife de chorizo, sal gruesa, pimienta",
                            Nombre = "Bife de chorizo",
                            Precio = 1500,
                            Preparacion = "Precalentar la parrilla a fuego medio-alto. Salar y pimentar el bife de chorizo al gusto. Colocar el bife en la parrilla y cocinar por 4-5 minutos de cada lado para un término medio. Dejar reposar el bife por unos minutos antes de cortarlo y servirlo c...",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 8,
                            Imagen = "https://th.bing.com/th/id/OIP.Os17j7OwByy5KCaluxoSowHaEo?pid=ImgDet&rs=1",
                            Ingredientes = "carne (lomo o entraña), cebolla, morrón, tomates cherry, aceite de oliva, sal, pimienta",
                            Nombre = "Brochette de carne y verduras",
                            Precio = 950,
                            Preparacion = "Cortar la carne en cubos y las verduras en trozos del mismo tamaño. En un recipiente, mezclar el aceite de oliva con sal y pimienta al gusto. Insertar los cubos de carne y las verduras en palillos de brochette alternando entre carne y verduras. Precale...",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 9,
                            Imagen = "https://th.bing.com/th/id/OIP.Xlx7oZVd_khsvg4O92O6DgHaE8?pid=ImgDet&rs=1",
                            Ingredientes = "salsa de tomate, mozzarella, albahaca fresca",
                            Nombre = "Pizza Margherita",
                            Precio = 1500,
                            Preparacion = "Precalentar el horno a 250°C. Extender la masa de pizza y cubrirla con la salsa de tomate. Agregar la mozzarella y espolvorear albahaca fresca al gusto. Hornear durante 10-12 minutos o hasta que la pizza esté dorada y crujiente. Servir caliente.",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 10,
                            Imagen = "https://th.bing.com/th/id/OIP.bj9ikcQ_3kP7VbipYtFnfgHaFC?pid=ImgDet&rs=1",
                            Ingredientes = "salsa de tomate, mozzarella, jamón, champiñones",
                            Nombre = "Pizza de jamón y hongos",
                            Precio = 1600,
                            Preparacion = "Precalentar el horno a 250°C. Extender la masa de pizza y cubrirla con la salsa de tomate. Agregar la mozzarella y luego el jamón y los champiñones cortados en rodajas. Hornear durante 10-12 minutos o hasta que la pizza esté dorada y crujiente. Servir ...",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 11,
                            Imagen = "https://th.bing.com/th/id/OIP.ntyZXTN9XOti6HYA3RTj6AHaFj?pid=ImgDet&rs=1",
                            Ingredientes = "pan de molde, pollo asado, queso cheddar, lechuga, tomate, mayonesa",
                            Nombre = "Sandwich de pollo y queso",
                            Precio = 900,
                            Preparacion = "Tostar el pan de molde en una sartén o tostadora. En una sartén aparte, calentar el pollo asado y añadir el queso cheddar hasta que se derrita. Colocar la lechuga y el tomate en una rebanada de pan, luego añadir el pollo y el queso derretido. Cubrir co...",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaId = 12,
                            Imagen = "https://enteratedelicias.com/wp-content/uploads/2022/03/cuantas-calorias-tiene-un-sandwich-de-jamon-y-queso.jpg",
                            Ingredientes = "pan francés, jamón cocido, queso provolone, tomate, lechuga, mayonesa",
                            Nombre = "Sandwich de jamón y queso",
                            Precio = 650,
                            Preparacion = "Cortar el pan francés en dos y tostarlo ligeramente en una sartén. Añadir el jamón y el queso provolone, y ponerlo a gratinar en el horno durante unos minutos. Agregar el tomate y la lechuga al gusto, y cubrir con la mayonesa antes de cerrar el sandwich.",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaId = 13,
                            Imagen = "https://okdiario.com/img/recetas/2015/08/30/ensalada-cesar.jpg",
                            Ingredientes = "lechuga, pollo asado, croutones, queso parmesano, aderezo César",
                            Nombre = "Ensalada César",
                            Precio = 650,
                            Preparacion = "Lavar y picar la lechuga, y colocarla en un bol. Cortar el pollo asado en trozos pequeños y agregarlos a la ensalada. Añadir los croutones y el queso parmesano. Cubrir con el aderezo César y mezclar bien.",
                            TipoMercaderiaId = 7
                        },
                        new
                        {
                            MercaderiaId = 14,
                            Imagen = "https://th.bing.com/th/id/OIP.-Kjln5nFsQ53ho-3sXaMJAHaE8?pid=ImgDet&rs=1",
                            Ingredientes = "lechuga, salmón ahumado, huevo duro, cebolla morada, tomate cherry, aceitunas, vinagreta de limón",
                            Nombre = "Ensalada de salmón",
                            Precio = 750,
                            Preparacion = "Lavar y picar la lechuga, y colocarla en un bol. Agregar el salmón ahumado cortado en trozos pequeños, los huevos duros picados, la cebolla morada en rodajas finas, los tomates cherry cortados por la mitad y las aceitunas. Cubrir con la vinagreta de li...",
                            TipoMercaderiaId = 7
                        },
                        new
                        {
                            MercaderiaId = 15,
                            Imagen = "https://th.bing.com/th/id/OIP.EOZRV17gk8fwRwLpm8SVTQHaHa?pid=ImgDet&rs=1",
                            Ingredientes = "limones, azúcar, agua, hielo",
                            Nombre = "Limonada natural",
                            Precio = 350,
                            Preparacion = "Cortar los limones en mitades y exprimir el jugo en una jarra. Agregar azúcar al gusto y mezclar bien. Añadir agua fría y hielo, y revolver hasta que se disuelva el azúcar. Servir en vasos con hielo.",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 16,
                            Imagen = "https://th.bing.com/th/id/OIP.-ZnJCFtxcJvHNcRitA2_eAHaHa?pid=ImgDet&rs=1",
                            Ingredientes = "agua con gas, frutos rojos (frambuesas, moras, arándanos), menta fresca",
                            Nombre = "Agua saborizada de frutos rojos",
                            Precio = 400,
                            Preparacion = "En una jarra, colocar los frutos rojos y la menta fresca. Agregar agua con gas y mezclar bien. Dejar reposar en la nevera por al menos una hora antes de servir para que los sabores se integren. Servir en vasos con hielo.",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 17,
                            Imagen = "https://s3-us-west-2.amazonaws.com/craftbeerdotcom/wp-content/uploads/2016/02/01141533/New-IPA-feature.jpg",
                            Ingredientes = "agua, maltas (pale ale, caramelo), lúpulos (Citra, Centennial), levadura",
                            Nombre = "India Pale Ale",
                            Precio = 900,
                            Preparacion = "En una olla, calentar agua hasta alcanzar la temperatura adecuada. Agregar las maltas y dejar reposar durante una hora. Luego, agregar los lúpulos y dejar hervir durante una hora más. Por último, agregar la levadura y dejar fermentar durante una semana...",
                            TipoMercaderiaId = 9
                        },
                        new
                        {
                            MercaderiaId = 18,
                            Imagen = "https://images-na.ssl-images-amazon.com/images/I/41Er65V%2BEeL.jpg",
                            Ingredientes = "agua, maltas (pale ale, chocolate, caramelo), lúpulos (Nugget), levadura",
                            Nombre = "Stout",
                            Precio = 900,
                            Preparacion = "En una olla, calentar agua hasta alcanzar la temperatura adecuada. Agregar las maltas y dejar reposar durante una hora. Luego, agregar los lúpulos y dejar hervir durante una hora más. Por último, agregar la levadura y dejar fermentar durante una semana...",
                            TipoMercaderiaId = 9
                        },
                        new
                        {
                            MercaderiaId = 19,
                            Imagen = "https://th.bing.com/th/id/OIP.xRsfgcAkr1VfqXJ2WFVXXAHaEK?pid=ImgDet&rs=1",
                            Ingredientes = "galletas de vainilla, queso crema, azúcar, huevos, crema de leche, frutos rojos",
                            Nombre = "Cheesecake de frutos rojos",
                            Precio = 800,
                            Preparacion = "Triturar las galletas y mezclarlas con mantequilla derretida. Cubrir un molde con esta mezcla y reservar en la nevera. Batir el queso crema con el azúcar y añadir los huevos, uno a uno, sin dejar de batir. Incorporar la crema de leche y mezclar bien. V...",
                            TipoMercaderiaId = 10
                        },
                        new
                        {
                            MercaderiaId = 20,
                            Imagen = "https://www.yummytummyaarthi.com/wp-content/uploads/2015/09/4-2.jpg",
                            Ingredientes = "harina, cacao en polvo, azúcar, huevos, aceite de girasol, avellanas, crema de leche",
                            Nombre = "Torta de chocolate y avellanas",
                            Precio = 900,
                            Preparacion = "En un bol, mezclar la harina con el cacao y el azúcar. Añadir los huevos y el aceite de girasol y mezclar hasta obtener una masa homogénea. Agregar las avellanas picadas y mezclar bien. Verter la masa en un molde y hornear durante unos 35 minutos a 180...",
                            TipoMercaderiaId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.TipoMercaderia", b =>
                {
                    b.Property<int>("TipoMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoMercaderiaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipoMercaderiaId");

                    b.ToTable("TipoMercaderia", (string)null);

                    b.HasData(
                        new
                        {
                            TipoMercaderiaId = 1,
                            Descripcion = "Entrada"
                        },
                        new
                        {
                            TipoMercaderiaId = 2,
                            Descripcion = "Minutas"
                        },
                        new
                        {
                            TipoMercaderiaId = 3,
                            Descripcion = "Pastas"
                        },
                        new
                        {
                            TipoMercaderiaId = 4,
                            Descripcion = "Parrilla"
                        },
                        new
                        {
                            TipoMercaderiaId = 5,
                            Descripcion = "Pizzas"
                        },
                        new
                        {
                            TipoMercaderiaId = 6,
                            Descripcion = "Sandwich"
                        },
                        new
                        {
                            TipoMercaderiaId = 7,
                            Descripcion = "Ensaladas"
                        },
                        new
                        {
                            TipoMercaderiaId = 8,
                            Descripcion = "Bebidas"
                        },
                        new
                        {
                            TipoMercaderiaId = 9,
                            Descripcion = "Cerveza Artesanal"
                        },
                        new
                        {
                            TipoMercaderiaId = 10,
                            Descripcion = "Postres"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.HasOne("Domain.Entities.FormaEntrega", "FormaEntrega")
                        .WithMany("Comanda")
                        .HasForeignKey("FormaEntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaEntrega");
                });

            modelBuilder.Entity("Domain.Entities.ComandaMercaderia", b =>
                {
                    b.HasOne("Domain.Entities.Comanda", "Comanda")
                        .WithMany("ComandaMercaderia")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Mercaderia", "Mercaderia")
                        .WithMany("ComandaMercaderia")
                        .HasForeignKey("MercaderiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Mercaderia");
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.HasOne("Domain.Entities.TipoMercaderia", "TipoMercaderia")
                        .WithMany("Mercaderia")
                        .HasForeignKey("TipoMercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoMercaderia");
                });

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.Navigation("ComandaMercaderia");
                });

            modelBuilder.Entity("Domain.Entities.FormaEntrega", b =>
                {
                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.Navigation("ComandaMercaderia");
                });

            modelBuilder.Entity("Domain.Entities.TipoMercaderia", b =>
                {
                    b.Navigation("Mercaderia");
                });
#pragma warning restore 612, 618
        }
    }
}
